// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/ova-joke-api/ova-joke-api.proto

package ova_joke_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Author struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Author) Reset() {
	*x = Author{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ova_joke_api_ova_joke_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_api_ova_joke_api_ova_joke_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_api_ova_joke_api_ova_joke_api_proto_rawDescGZIP(), []int{0}
}

func (x *Author) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Joke struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text   string  `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Author *Author `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *Joke) Reset() {
	*x = Joke{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ova_joke_api_ova_joke_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Joke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Joke) ProtoMessage() {}

func (x *Joke) ProtoReflect() protoreflect.Message {
	mi := &file_api_ova_joke_api_ova_joke_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Joke.ProtoReflect.Descriptor instead.
func (*Joke) Descriptor() ([]byte, []int) {
	return file_api_ova_joke_api_ova_joke_api_proto_rawDescGZIP(), []int{1}
}

func (x *Joke) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Joke) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Joke) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type CreateJokeRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text   string  `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Author *Author `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *CreateJokeRequestV1) Reset() {
	*x = CreateJokeRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ova_joke_api_ova_joke_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateJokeRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJokeRequestV1) ProtoMessage() {}

func (x *CreateJokeRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ova_joke_api_ova_joke_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJokeRequestV1.ProtoReflect.Descriptor instead.
func (*CreateJokeRequestV1) Descriptor() ([]byte, []int) {
	return file_api_ova_joke_api_ova_joke_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreateJokeRequestV1) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreateJokeRequestV1) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type CreateJokeResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateJokeResponseV1) Reset() {
	*x = CreateJokeResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ova_joke_api_ova_joke_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateJokeResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJokeResponseV1) ProtoMessage() {}

func (x *CreateJokeResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ova_joke_api_ova_joke_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJokeResponseV1.ProtoReflect.Descriptor instead.
func (*CreateJokeResponseV1) Descriptor() ([]byte, []int) {
	return file_api_ova_joke_api_ova_joke_api_proto_rawDescGZIP(), []int{3}
}

func (x *CreateJokeResponseV1) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DescribeJokeRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DescribeJokeRequestV1) Reset() {
	*x = DescribeJokeRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ova_joke_api_ova_joke_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeJokeRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeJokeRequestV1) ProtoMessage() {}

func (x *DescribeJokeRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ova_joke_api_ova_joke_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeJokeRequestV1.ProtoReflect.Descriptor instead.
func (*DescribeJokeRequestV1) Descriptor() ([]byte, []int) {
	return file_api_ova_joke_api_ova_joke_api_proto_rawDescGZIP(), []int{4}
}

func (x *DescribeJokeRequestV1) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DescribeJokeResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text   string  `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Author *Author `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *DescribeJokeResponseV1) Reset() {
	*x = DescribeJokeResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ova_joke_api_ova_joke_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeJokeResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeJokeResponseV1) ProtoMessage() {}

func (x *DescribeJokeResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ova_joke_api_ova_joke_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeJokeResponseV1.ProtoReflect.Descriptor instead.
func (*DescribeJokeResponseV1) Descriptor() ([]byte, []int) {
	return file_api_ova_joke_api_ova_joke_api_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeJokeResponseV1) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DescribeJokeResponseV1) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DescribeJokeResponseV1) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type ListJokeRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListJokeRequestV1) Reset() {
	*x = ListJokeRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ova_joke_api_ova_joke_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListJokeRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJokeRequestV1) ProtoMessage() {}

func (x *ListJokeRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ova_joke_api_ova_joke_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJokeRequestV1.ProtoReflect.Descriptor instead.
func (*ListJokeRequestV1) Descriptor() ([]byte, []int) {
	return file_api_ova_joke_api_ova_joke_api_proto_rawDescGZIP(), []int{6}
}

type ListJokeResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jokes []*Joke `protobuf:"bytes,1,rep,name=jokes,proto3" json:"jokes,omitempty"`
}

func (x *ListJokeResponseV1) Reset() {
	*x = ListJokeResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ova_joke_api_ova_joke_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListJokeResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJokeResponseV1) ProtoMessage() {}

func (x *ListJokeResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ova_joke_api_ova_joke_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJokeResponseV1.ProtoReflect.Descriptor instead.
func (*ListJokeResponseV1) Descriptor() ([]byte, []int) {
	return file_api_ova_joke_api_ova_joke_api_proto_rawDescGZIP(), []int{7}
}

func (x *ListJokeResponseV1) GetJokes() []*Joke {
	if x != nil {
		return x.Jokes
	}
	return nil
}

type RemoveJokeRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveJokeRequestV1) Reset() {
	*x = RemoveJokeRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ova_joke_api_ova_joke_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveJokeRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveJokeRequestV1) ProtoMessage() {}

func (x *RemoveJokeRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ova_joke_api_ova_joke_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveJokeRequestV1.ProtoReflect.Descriptor instead.
func (*RemoveJokeRequestV1) Descriptor() ([]byte, []int) {
	return file_api_ova_joke_api_ova_joke_api_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveJokeRequestV1) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveJokeResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveJokeResponseV1) Reset() {
	*x = RemoveJokeResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ova_joke_api_ova_joke_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveJokeResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveJokeResponseV1) ProtoMessage() {}

func (x *RemoveJokeResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_ova_joke_api_ova_joke_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveJokeResponseV1.ProtoReflect.Descriptor instead.
func (*RemoveJokeResponseV1) Descriptor() ([]byte, []int) {
	return file_api_ova_joke_api_ova_joke_api_proto_rawDescGZIP(), []int{9}
}

var File_api_ova_joke_api_ova_joke_api_proto protoreflect.FileDescriptor

var file_api_ova_joke_api_ova_joke_api_proto_rawDesc = []byte{
	0x0a, 0x23, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x76, 0x61, 0x2d, 0x6a, 0x6f, 0x6b, 0x65, 0x2d, 0x61,
	0x70, 0x69, 0x2f, 0x6f, 0x76, 0x61, 0x2d, 0x6a, 0x6f, 0x6b, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6f, 0x7a, 0x6f, 0x6e, 0x76, 0x61, 0x2e, 0x6f, 0x76,
	0x61, 0x5f, 0x6a, 0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x22, 0x2c, 0x0a, 0x06, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x5f, 0x0a, 0x04, 0x4a, 0x6f, 0x6b, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x33, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x76, 0x61, 0x2e, 0x6f, 0x76,
	0x61, 0x5f, 0x6a, 0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x5e, 0x0a, 0x13, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4a, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x33, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x76, 0x61, 0x2e, 0x6f, 0x76,
	0x61, 0x5f, 0x6a, 0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x26, 0x0a, 0x14, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4a, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56,
	0x31, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x27, 0x0a, 0x15, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4a, 0x6f, 0x6b,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x71, 0x0a, 0x16, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4a, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x56, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x33, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x76,
	0x61, 0x2e, 0x6f, 0x76, 0x61, 0x5f, 0x6a, 0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x13, 0x0a,
	0x11, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x56, 0x31, 0x22, 0x45, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x6f, 0x6b, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x12, 0x2f, 0x0a, 0x05, 0x6a, 0x6f, 0x6b, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x76, 0x61,
	0x2e, 0x6f, 0x76, 0x61, 0x5f, 0x6a, 0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4a, 0x6f,
	0x6b, 0x65, 0x52, 0x05, 0x6a, 0x6f, 0x6b, 0x65, 0x73, 0x22, 0x25, 0x0a, 0x13, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x4a, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x16, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4a, 0x6f, 0x6b, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x32, 0xa9, 0x03, 0x0a, 0x0b, 0x4a, 0x6f, 0x6b,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x65, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4a, 0x6f, 0x6b, 0x65, 0x56, 0x31, 0x12, 0x28, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x76,
	0x61, 0x2e, 0x6f, 0x76, 0x61, 0x5f, 0x6a, 0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x56, 0x31, 0x1a, 0x29, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x76, 0x61, 0x2e, 0x6f, 0x76, 0x61, 0x5f,
	0x6a, 0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a,
	0x6f, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x22, 0x00, 0x12,
	0x6b, 0x0a, 0x0e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4a, 0x6f, 0x6b, 0x65, 0x56,
	0x31, 0x12, 0x2a, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x76, 0x61, 0x2e, 0x6f, 0x76, 0x61, 0x5f, 0x6a,
	0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x4a, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x1a, 0x2b, 0x2e,
	0x6f, 0x7a, 0x6f, 0x6e, 0x76, 0x61, 0x2e, 0x6f, 0x76, 0x61, 0x5f, 0x6a, 0x6f, 0x6b, 0x65, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4a, 0x6f, 0x6b, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x0a,
	0x4c, 0x69, 0x73, 0x74, 0x4a, 0x6f, 0x6b, 0x65, 0x56, 0x31, 0x12, 0x26, 0x2e, 0x6f, 0x7a, 0x6f,
	0x6e, 0x76, 0x61, 0x2e, 0x6f, 0x76, 0x61, 0x5f, 0x6a, 0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x56, 0x31, 0x1a, 0x27, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x76, 0x61, 0x2e, 0x6f, 0x76, 0x61, 0x5f,
	0x6a, 0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x6f, 0x6b,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x22, 0x00, 0x12, 0x65, 0x0a,
	0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4a, 0x6f, 0x6b, 0x65, 0x56, 0x31, 0x12, 0x28, 0x2e,
	0x6f, 0x7a, 0x6f, 0x6e, 0x76, 0x61, 0x2e, 0x6f, 0x76, 0x61, 0x5f, 0x6a, 0x6f, 0x6b, 0x65, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4a, 0x6f, 0x6b, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x1a, 0x29, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x76, 0x61,
	0x2e, 0x6f, 0x76, 0x61, 0x5f, 0x6a, 0x6f, 0x6b, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x4a, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x56, 0x31, 0x22, 0x00, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6f, 0x7a, 0x6f, 0x6e, 0x76, 0x61, 0x2f, 0x6f, 0x76, 0x61, 0x2d, 0x6a, 0x6f,
	0x6b, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6f, 0x76, 0x61, 0x2d, 0x6a,
	0x6f, 0x6b, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x3b, 0x6f, 0x76, 0x61, 0x5f, 0x6a, 0x6f, 0x6b, 0x65,
	0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_ova_joke_api_ova_joke_api_proto_rawDescOnce sync.Once
	file_api_ova_joke_api_ova_joke_api_proto_rawDescData = file_api_ova_joke_api_ova_joke_api_proto_rawDesc
)

func file_api_ova_joke_api_ova_joke_api_proto_rawDescGZIP() []byte {
	file_api_ova_joke_api_ova_joke_api_proto_rawDescOnce.Do(func() {
		file_api_ova_joke_api_ova_joke_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ova_joke_api_ova_joke_api_proto_rawDescData)
	})
	return file_api_ova_joke_api_ova_joke_api_proto_rawDescData
}

var file_api_ova_joke_api_ova_joke_api_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_ova_joke_api_ova_joke_api_proto_goTypes = []interface{}{
	(*Author)(nil),                 // 0: ozonva.ova_joke_api.Author
	(*Joke)(nil),                   // 1: ozonva.ova_joke_api.Joke
	(*CreateJokeRequestV1)(nil),    // 2: ozonva.ova_joke_api.CreateJokeRequestV1
	(*CreateJokeResponseV1)(nil),   // 3: ozonva.ova_joke_api.CreateJokeResponseV1
	(*DescribeJokeRequestV1)(nil),  // 4: ozonva.ova_joke_api.DescribeJokeRequestV1
	(*DescribeJokeResponseV1)(nil), // 5: ozonva.ova_joke_api.DescribeJokeResponseV1
	(*ListJokeRequestV1)(nil),      // 6: ozonva.ova_joke_api.ListJokeRequestV1
	(*ListJokeResponseV1)(nil),     // 7: ozonva.ova_joke_api.ListJokeResponseV1
	(*RemoveJokeRequestV1)(nil),    // 8: ozonva.ova_joke_api.RemoveJokeRequestV1
	(*RemoveJokeResponseV1)(nil),   // 9: ozonva.ova_joke_api.RemoveJokeResponseV1
}
var file_api_ova_joke_api_ova_joke_api_proto_depIdxs = []int32{
	0, // 0: ozonva.ova_joke_api.Joke.author:type_name -> ozonva.ova_joke_api.Author
	0, // 1: ozonva.ova_joke_api.CreateJokeRequestV1.author:type_name -> ozonva.ova_joke_api.Author
	0, // 2: ozonva.ova_joke_api.DescribeJokeResponseV1.author:type_name -> ozonva.ova_joke_api.Author
	1, // 3: ozonva.ova_joke_api.ListJokeResponseV1.jokes:type_name -> ozonva.ova_joke_api.Joke
	2, // 4: ozonva.ova_joke_api.JokeService.CreateJokeV1:input_type -> ozonva.ova_joke_api.CreateJokeRequestV1
	4, // 5: ozonva.ova_joke_api.JokeService.DescribeJokeV1:input_type -> ozonva.ova_joke_api.DescribeJokeRequestV1
	6, // 6: ozonva.ova_joke_api.JokeService.ListJokeV1:input_type -> ozonva.ova_joke_api.ListJokeRequestV1
	8, // 7: ozonva.ova_joke_api.JokeService.RemoveJokeV1:input_type -> ozonva.ova_joke_api.RemoveJokeRequestV1
	3, // 8: ozonva.ova_joke_api.JokeService.CreateJokeV1:output_type -> ozonva.ova_joke_api.CreateJokeResponseV1
	5, // 9: ozonva.ova_joke_api.JokeService.DescribeJokeV1:output_type -> ozonva.ova_joke_api.DescribeJokeResponseV1
	7, // 10: ozonva.ova_joke_api.JokeService.ListJokeV1:output_type -> ozonva.ova_joke_api.ListJokeResponseV1
	9, // 11: ozonva.ova_joke_api.JokeService.RemoveJokeV1:output_type -> ozonva.ova_joke_api.RemoveJokeResponseV1
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_ova_joke_api_ova_joke_api_proto_init() }
func file_api_ova_joke_api_ova_joke_api_proto_init() {
	if File_api_ova_joke_api_ova_joke_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ova_joke_api_ova_joke_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Author); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ova_joke_api_ova_joke_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Joke); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ova_joke_api_ova_joke_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateJokeRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ova_joke_api_ova_joke_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateJokeResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ova_joke_api_ova_joke_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeJokeRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ova_joke_api_ova_joke_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeJokeResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ova_joke_api_ova_joke_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListJokeRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ova_joke_api_ova_joke_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListJokeResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ova_joke_api_ova_joke_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveJokeRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ova_joke_api_ova_joke_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveJokeResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ova_joke_api_ova_joke_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ova_joke_api_ova_joke_api_proto_goTypes,
		DependencyIndexes: file_api_ova_joke_api_ova_joke_api_proto_depIdxs,
		MessageInfos:      file_api_ova_joke_api_ova_joke_api_proto_msgTypes,
	}.Build()
	File_api_ova_joke_api_ova_joke_api_proto = out.File
	file_api_ova_joke_api_ova_joke_api_proto_rawDesc = nil
	file_api_ova_joke_api_ova_joke_api_proto_goTypes = nil
	file_api_ova_joke_api_ova_joke_api_proto_depIdxs = nil
}
