version: '3.1'

services:
  db:
    image: postgres
#    restart: always
    volumes:
      - ./.var/psqldata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
