{
 "title": "OVA Joke API",
 "time": { "from": "2021-09-07T11:03:29.837Z", "to": "2021-09-07T11:39:14.242Z" },
 "panels": [
  {
   "title": "gRPC requests count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "joke_api_create_total" },
    { "expr": "joke_api_describe_total" },
    { "expr": "joke_api_list_total" },
    { "expr": "joke_api_multi_create_total" },
    { "expr": "joke_api_remove_total" },
    { "expr": "joke_api_total" },
    { "expr": "joke_api_update_total" }
   ]
  },
  {
   "title": "Describe requests rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "joke_api_describe_total" },
    {
     "expr": "joke_api_describe_not_exists_total"
    },
    {
     "expr": "joke_api_describe_not_exists_total/joke_api_describe_total"
    }
   ]
  },
  {
   "title": "Multi create rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "joke_api_multi_create_total" },
    {
     "expr": "joke_api_multi_create_failed_total"
    },
    {
     "expr": "joke_api_multi_create_total/joke_api_multi_create_failed_total"
    }
   ]
  }
 ]
}